### ISSUE TITLE
Conpuerta Logicas - Equipo Erick Ramos

### ISSUE THREAD

**Issue by irving1613** [SistemasTecTlaxiaco/compuertas-logicas-equipo-erick-ramos#1]
[COMPUERTAS LÓGICAS.pdf](https://github.com/SistemasTecTlaxiaco/compuertas-logicas-equipo-erick-ramos/files/7731207/COMPUERTAS.LOGICAS.pdf)

**Comment by 71santiago7** [comment]
[Uploading COMPUERTAS LÓGICAS.pdf…]()

**Comment by lourdeshernandez2003** [comment]
25/25 (excelente portada).
15/25( No cuenta con objetivo, material, descripción de cada una de las actividades y tampoco los resultados).
17/25 (No tiene descripción las actividades y les faltó realizar correctamente los ejercicios).
17/25 (No describe los resultados y la conclusión está incompleta).
Total: 74/100
CALIFICACIÓN: 14.8

**Comment by lourdeshernandez2003** [comment]
25/25 (excelente portada).
15/25( No cuenta con objetivo, material, descripción de cada una de las actividades y tampoco los resultados).
17/25 (No tiene descripción las actividades y les faltó realizar correctamente los ejercicios).
17/25 (No describe los resultados y la conclusión está incompleta).
Total 74
Calificacion =22.2/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado
